### ISSUE TITLE
babel-node use

### ISSUE THREAD

**Issue by headwinds** [ahmadnassri/pretty-exceptions#2]
I'm using babel-cli (babel-node) to be able use es6/7 features on the server

when I run
```
node --require pretty-exceptions server.js
```
I get ```SyntaxError: Unexpected token import``` probably due to babel-node I would think...  what would you recommend to run pretty-exceptions with babel-cli?

**Comment by ahmadnassri** [comment]
it seems `babel-node` does not support all node flags, and there's an [open issue](https://github.com/babel/babel/pull/5599) to track this

you could use `babel` directly AND `pretty-exceptions` (essentially replacing the need for `babel-node`):

```shell
node --require pretty-exceptions --require babel-register
```

**Comment by headwinds** [comment]
thanks!
