### ISSUE TITLE
Export the render function without the handler

### ISSUE THREAD

**Issue by Vincz** [ahmadnassri/pretty-exceptions#5]
Hi!
The error rendering is really nice with your package and I'd like to use it in one of my project.
I'd like to be able to use only the rendering part, without the handler (It's a server and I don't want to exit the process if an error occurs).

Something like :

    const renderError = require('pretty-exceptions/render');

    try {
        // failing code
    } catch(error) {
        renderError(error);
    }

Thanks !

**Comment by ahmadnassri** [comment]
good idea ...

**Comment by ahmadnassri** [comment]
done, released in [v1.4.0](https://github.com/ahmadnassri/pretty-exceptions/releases/tag/v1.4.0)
